# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"


$script = <<SCRIPT
docker version | grep 'Client version: 1.' || curl -s https://get.docker.io/ubuntu/ | sudo sh

sudo docker pull otahi/lbspec-test
sudo docker stop srcnode dstnode
sudo docker rm srcnode dstnode
sudo docker run -p 20022:22 -d --name dstnode otahi/lbspec-test
sudo docker run -p 10022:22 -d --link dstnode:dstnode --name srcnode otahi/lbspec-test
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu14.04'

  config.vm.provider "virtualbox" do |_v|
    config.vm.box_url =
      'http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
  end
  config.vm.network "private_network", ip: "192.168.254.254"

  config.vm.provision "shell", inline: $script
end
